### ISSUE TITLE
Does ASF-Achievement-Manager work on ASM-generic version 6.0.6.4?

### ISSUE THREAD

**Issue by Levk39** [Rudokhvist/ASF-Achievement-Manager#31]
I have ASF-generic V6.0.6.4 installed. I wanted to add the ASF-Achievement-Manager plugin, but it was not added (ASF did not see it) how do I set up this plugin?

**Comment by Rudokhvist** [comment]
1) Did you unpack ASF-Achievement-Manager.zip to the `config` folder of your ASF installation? 
2) Did you restart ASF after that?
3) If your answer to 1 and 2 is yes, show full log.txt from your asf folder.

**Comment by Levk39** [comment]
Thanks, I unpacked the archive incorrectly, leaving the dll file in the folder. The plugin is now working
